source 'https://rubygems.org'

ruby '>= 3.1.0'

gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'
gem 'rack-cors', '~> 2.0'
gem 'httparty', '~> 0.21'
gem 'json', '~> 2.6'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
  gem 'rubocop', '~> 1.57'
  gem 'rubocop-rspec', '~> 2.24'
end

